version: '3.1'

services:
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: server
    ports:
      - 8080:80
    volumes:
      - .:/var/www/docker-lamp-php-5
      - ./logs/apache2:/var/log/apache2

  db:
    image: mysql:5.5
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=some_password
      - MYSQL_DATABASE=some_db
      - MYSQL_USER=some_user
      - MYSQL_PASSWORD=some_password
    ports:
      - 8306:3306
    volumes:
      - /var/lib/mysql/db:/var/lib/mysql/db
      
  rclone-dlna-server:
    container_name: rclone-dlna-server

    image: rclone/rclone
    command:
  # Tweak here rclone's command line switches:
  #    - "--config"
  #    - "/path/to/mounted/rclone.conf"
      - "--verbose"
      - "serve"
      - "dlna"
      - "remote:/"
      - "--name"
      - "myDLNA server"
      - "--read-only"
  #    - "--no-modtime"
  #    - "--no-checksum"

    restart: unless-stopped

    # Use host networking for simplicity with DLNA broadcasts
    # and to avoid having to do port mapping.
    net: host

    # Here you have to map your host's rclone.conf directory to
    # container's /root/.config/rclone/ dir (R/O).
    # If you have any remote referencing local files, you have to
    # map them here, too.
    volumes:
      - ~/.config/rclone/:/root/.config/rclone/:ro
